name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --clean --noconfirm --windowed --name "AutoDriveDESI" --add-data "7z.exe;." --add-data "credentials.json;." --collect-all customtkinter main_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoDriveDESI-Windows
          path: dist/AutoDriveDESI/
