name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Check files
        run: |
          ls bin/windows/7z.exe
          ls credentials.json

      - name: Build EXE
        run: |
          python -m PyInstaller --clean --noconfirm --windowed `
            --name "AutoDriveDESI" `
            --add-data "bin/windows/7z.exe;." `
            --add-data "credentials.json;." `
            --collect-all customtkinter `
            main_app.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AutoDriveDESI-Windows
          path: dist/AutoDriveDESI/
